<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1510" started-at="2017-11-06T01:24:49Z" finished-at="2017-11-06T01:24:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1510" started-at="2017-11-06T01:24:49Z" finished-at="2017-11-06T01:24:51Z">
      <class name="WebAppTest.HeadlessBrowserTest">
        <test-method status="PASS" signature="verifySimplWebAppTitle()[pri:0, instance:WebAppTest.HeadlessBrowserTest@6eebc39e]" name="verifySimplWebAppTitle" duration-ms="1403" started-at="2017-11-05T20:24:49Z" finished-at="2017-11-05T20:24:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySimplWebAppTitle -->
        <test-method status="FAIL" signature="verifySimplWebAppTitleFail()[pri:0, instance:WebAppTest.HeadlessBrowserTest@6eebc39e]" name="verifySimplWebAppTitleFail" duration-ms="88" started-at="2017-11-05T20:24:51Z" finished-at="2017-11-05T20:24:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at WebAppTest.HeadlessBrowserTest.verifySimplWebAppTitleFail(HeadlessBrowserTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySimplWebAppTitleFail -->
      </class> <!-- WebAppTest.HeadlessBrowserTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
